# Generated by Django 5.1.1 on 2025-03-19 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventtickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'EventTickets',
                'db_table': 'EventTickets',
            },
        ),
        migrations.CreateModel(
            name='Eventtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'EventTypes',
                'db_table': 'EventTypes',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Organizers',
                'db_table': 'Organizers',
            },
        ),
        migrations.CreateModel(
            name='Tickettypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TicketTypes',
                'db_table': 'TicketTypes',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.eventtypes')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.locations')),
                ('organizer', models.ManyToManyField(to='home.organizers')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.IntegerField()),
                ('payment_method', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.events')),
                ('ticket', models.ManyToManyField(to='home.eventtickets')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Registrations',
                'db_table': 'Registrations',
            },
        ),
        migrations.AddField(
            model_name='eventtickets',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.tickettypes'),
        ),
    ]
