# Generated by Django 5.1.1 on 2025-03-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ticket_types',
            field=models.ManyToManyField(to='home.eventtickets'),
        ),
        migrations.AddField(
            model_name='registrations',
            name='quantity_tickets',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='ticket',
        ),
        migrations.AddField(
            model_name='registrations',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.eventtickets'),
        ),
    ]
