# Generated by Django 5.1.1 on 2025-03-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_events_ticket_types_registrations_quantity_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='quantity_tickets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.eventtickets'),
        ),
    ]
