# Generated by Django 5.1.1 on 2025-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_registrations_quantity_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtickets',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='eventtickets',
            name='ticket_type_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Tickettypes',
        ),
    ]
