# Generated by Django 5.1.1 on 2025-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_eventtickets_ticket_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtickets',
            name='ticket_type_name',
            field=models.CharField(max_length=255),
        ),
    ]
